Completed translation
yuaanlin/nextjs.tw pull request #36
Opened 2022-09-07 16:23 UTC by AndreaFan123

Completed TypeScript and fast-fresh translation

2022-09-08 04:24 UTC, yuaanlin requested changes
Hi, thanks for the contribution! There is some changes needed to let this PR be merged.

2022-09-08 04:24 UTC, yuaanlin commented on pages/docs/basic-features/fast-refresh.mdx
> +「快速重整」是 Next.js 的讓編輯的 React 組件獲得立即回饋的一個功能。**9.4 或更新的版本**中，這個功能在所有的 Next.js 應用程式是默認開啟的。隨著這個功能的開啟，幾乎所有的編輯都不會遺失組件的狀態而被快速地看見。
官方文件的話是不是不要用「快速重整」這種縮寫 XD
而且你上面明明就翻成「快速更新」，名詞可能要統一一下

2022-09-08 04:24 UTC, yuaanlin commented on pages/docs/basic-features/fast-refresh.mdx
> +「快速重整」是 Next.js 的讓編輯的 React 組件獲得立即回饋的一個功能。**9.4 或更新的版本**中，這個功能在所有的 Next.js 應用程式是默認開啟的。隨著這個功能的開啟，幾乎所有的編輯都不會遺失組件的狀態而被快速地看見。
這句話翻的有點不通順，試著讀懂原文以後用自己的話重新說一次看看

2022-09-08 04:24 UTC, yuaanlin commented on pages/docs/basic-features/fast-refresh.mdx
> +如果你在開發時不小心有一個語法錯誤，你可以修正並再一次儲存。此錯誤將會自動地消失，你將不需要重新載入應用程式，同時也**不會遺失組件狀態**。
我們統一把 `component` 翻譯成 `元件` 而不是 `組件`

2022-09-08 04:24 UTC, yuaanlin commented on pages/docs/basic-features/typescript.mdx
> +描述: Next.js 默認支援 TypeScript 以及為頁面和 API 內建的 types。這裡將會學習到如何在 Next.js 內使用 TypeScript。
`默認` 是簡體中文的用法，default 在繁體中文翻譯為 `預設`

2022-09-08 04:24 UTC, yuaanlin commented on pages/docs/basic-features/typescript.mdx
> +Next.js 提供包含零配置設定以及為了頁面、API 及更多的內建 types 的 [TypeScript](https://www.typescriptlang.org/) 整合體驗。
`zero-configuration` 翻譯成 `無需額外設定` 會比 `零配置` 更通順一些

2022-09-08 04:24 UTC, yuaanlin commented on pages/docs/basic-features/typescript.mdx
> +- [複製以及部署 TypeScript 啟動器](https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Fvercel%2Fnext.js%2Ftree%2Fcanary%2Fexamples%2Fwith-typescript&project-name=with-typescript&repository-
`starter` 指的是一個最簡單的專案模板，翻譯成 `啟動器` 有點奇怪

2022-09-08 11:33 UTC, AndreaFan123 commented on pages/docs/basic-features/fast-refresh.mdx
> +「快速重整」是 Next.js 的讓編輯的 React 組件獲得立即回饋的一個功能。**9.4 或更新的版本**中，這個功能在所有的 Next.js 應用程式是默認開啟的。隨著這個功能的開啟，幾乎所有的編輯都不會遺失組件的狀態而被快速地看見。
這句話我在重新順了一下，你看一下有沒有比較好 XD

2022-09-08 11:33 UTC, AndreaFan123 commented on pages/docs/basic-features/typescript.mdx
> +描述: Next.js 默認支援 TypeScript 以及為頁面和 API 內建的 types。這裡將會學習到如何在 Next.js 內使用 TypeScript。
Fixed.

2022-09-08 11:33 UTC, AndreaFan123 commented on pages/docs/basic-features/typescript.mdx
> +Next.js 提供包含零配置設定以及為了頁面、API 及更多的內建 types 的 [TypeScript](https://www.typescriptlang.org/) 整合體驗。
Fixed.

2022-09-09 05:03 UTC, AndreaFan123 commented on pages/docs/basic-features/typescript.mdx
> +- [複製以及部署 TypeScript 啟動器](https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Fvercel%2Fnext.js%2Ftree%2Fcanary%2Fexamples%2Fwith-typescript&project-name=with-typescript&repository-
fixed

2022-09-09 13:10 UTC, yuaanlin approved these changes

2022-09-09 13:10 UTC, merged