20220910_嘗試 pull draft request
yuaanlin/nextjs.tw pull request #42
Opened 2022-09-10 06:59 UTC by Nicolas19921107

20220910_嘗試 pull draft request

2022-09-10 13:59 UTC, yuaanlin requested changes
Hi, thanks for the contribution! There is some changes needed to let this PR be merged. Please see the comments below.

2022-09-10 13:59 UTC, yuaanlin commented on pages/learn/foundations/from-react-to-nextjs/getting-started-with-nextjs.mdx
> +取而代之的是，您可以在本地端使用套件管理工具 `npm` 來安裝這些套件
```suggestion
在安裝 Next.js 到您的專案前，您不再需要透過手動加入 `react` 與 `react-dom` 的 script 標籤的方式引入 React。取而代之的是，您可以在本地端使用套件管理工具 `npm` 來安裝這些套件。
```

2022-09-10 13:59 UTC, yuaanlin commented on pages/learn/foundations/from-react-to-nextjs/getting-started-with-nextjs.mdx
> +    }
```suggestion
//package.json
{

}
```

2022-09-10 13:59 UTC, yuaanlin commented on pages/learn/foundations/from-react-to-nextjs/getting-started-with-nextjs.mdx
> +此時在 `index.html` 中的程式碼均為 JSX 語法，為此您可將 `index.html` 的檔案類型由 .html 替換為 `.js` 或 `.jsx`。
在 Markdown 或 MDX 語法中，不同類型的區塊（比如說 Code Block 和一般文字）中間要空一行。

2022-09-10 13:59 UTC, yuaanlin commented on pages/learn/foundations/from-react-to-nextjs/getting-started-with-nextjs.mdx
> +看完前面對於程式碼上的變更，您或許已經理解使用 Next.js 的好處。您移除了 Babel Script， 體驗了不再需要多餘思考而配置的複雜工具。您也觀察到了[快速刷新]( Fast Refresh )的實際效果，而這些只是 Next.js 在眾多開發者體驗特色中的其中一項。
```suggestion
看完前面對於程式碼上的變更，您或許已經理解使用 Next.js 的好處。您移除了 Babel Script， 體驗了不再需要多餘思考而配置的複雜工具。您也觀察到了快速重新整理（ Fast Refresh ）的實際效果，而這些只是 Next.js 在眾多開發者體驗特色中的其中一項。
```

2022-09-10 13:59 UTC, yuaanlin commented on pages/learn/foundations/from-react-to-nextjs/getting-started-with-nextjs.mdx
> +<Button
```suggestion
/>

<Button
```

2022-09-10 13:59 UTC, yuaanlin commented on pages/learn/foundations/from-react-to-nextjs/getting-started-with-nextjs.mdx
>  />
這個應該放在大標題下面

2022-09-12 14:53 UTC, Nicolas19921107 reviewed
已調整

2022-09-14 01:13 UTC, yuaanlin requested changes

2022-09-14 01:13 UTC, yuaanlin commented on pages/learn/foundations/from-react-to-nextjs/getting-started-with-nextjs.mdx
> +    "/learn/foundations/from-react-to-nextjs/next-steps",
```suggestion
    '/learn/foundations/from-react-to-nextjs',
    '/learn/foundations/from-react-to-nextjs/getting-started-with-nextjs',
    '/learn/foundations/from-react-to-nextjs/next-steps',
```

2022-09-14 01:13 UTC, yuaanlin commented on pages/learn/foundations/from-react-to-nextjs/getting-started-with-nextjs.mdx
> +在安裝 Next.js 到你的專案前，你不再需要透過手動加入 `react` 與 `react-dom` 的 script 標籤的方式引入 React
```suggestion
在安裝 Next.js 到你的專案前，你不再需要透過手動加入 `react` 與 `react-dom` 的 script 標籤的方式引入 React 。
```

2022-09-14 01:13 UTC, yuaanlin commented on pages/learn/foundations/from-react-to-nextjs/getting-started-with-nextjs.mdx
> +在準備開發前，請先新增一個內容為空物件 `{}` 的 `package.json` 文檔。
```suggestion
在準備開發前，請先新增一個內容為空物件 `{}` 的 `package.json` 檔案。
```

2022-09-14 01:13 UTC, yuaanlin commented on pages/learn/foundations/from-react-to-nextjs/getting-started-with-nextjs.mdx
> +當安裝程序完成後，你可以在 `package.json` 文檔中，查看專案所有的相依套件與應用程式資訊：
```suggestion
當安裝程序完成後，你可以在 `package.json` 檔案中，查看專案所有的相依套件資訊：
```

2022-09-14 01:13 UTC, yuaanlin commented on pages/learn/foundations/from-react-to-nextjs/getting-started-with-nextjs.mdx
> +你可透過終端機運行 `npm run dev` 並開啟瀏覽器前往 [localhost:3000](localhost:3000) 以查看應用程式是否正常運作。接下來，你可以針對程式碼試著做些調整並儲存
```suggestion
你可透過終端機運行 `npm run dev` 並開啟瀏覽器前往 [localhost:3000](localhost:3000) 以查看應用程式是否正常運作。接下來，你可以針對程式碼試著做些調整並儲存。
```

2022-09-14 01:13 UTC, yuaanlin commented on pages/learn/foundations/from-react-to-nextjs/index.mdx
> +    "/learn/foundations/from-react-to-nextjs/next-steps"
```suggestion
    '/learn/foundations/from-react-to-nextjs',
    '/learn/foundations/from-react-to-nextjs/getting-started-with-nextjs',
    '/learn/foundations/from-react-to-nextjs/next-steps'
```

2022-09-14 01:13 UTC, yuaanlin commented on pages/learn/foundations/from-react-to-nextjs/next-steps.mdx
> +熟悉這些觀念有助你擴展相關的知識基礎，並可以更容易地學習到更多關於 Next.js 的進階功能
```suggestion
熟悉這些觀念有助你擴展相關的知識基礎，並可以更容易地學習到更多關於 Next.js 的進階功能。
```

2022-09-14 01:13 UTC, yuaanlin commented on pages/learn/foundations/from-react-to-nextjs/next-steps.mdx
> +<TranslatedBy githubUserNames={["st880517"]} />
```suggestion
<TranslatedBy githubUserNames={["Nicolas19921107"]} />
```

2022-09-14 01:13 UTC, yuaanlin commented on pages/learn/foundations/from-react-to-nextjs/index.mdx
> +<TranslatedBy githubUserNames={["st880517"]} />
```suggestion
<TranslatedBy githubUserNames={["Nicolas19921107"]} />
```

2022-09-14 01:13 UTC, yuaanlin commented on pages/learn/foundations/from-react-to-nextjs/getting-started-with-nextjs.mdx
> +<TranslatedBy githubUserNames={["st880517"]} />
```suggestion
<TranslatedBy githubUserNames={["Nicolas19921107"]} />
```

2022-09-14 23:57 UTC, yuaanlin approved these changes

2022-09-14 23:57 UTC, merged