Completed translations
yuaanlin/nextjs.tw pull request #46
Opened 2022-09-10 15:04 UTC by Danny101201

2022-09-12 05:37 UTC, yuaanlin requested changes
Hi, thanks for the contribution! There is some changes needed to let this PR be merged.

2022-09-12 05:37 UTC, yuaanlin commented on pages/docs/basic-features/data-fetching/overview.mdx
> -</div>
我覺得按照原本的寫法直接在 Markdown 使用 HTML 語法就好，不需要特別用 JSX 搞一個 component

2022-09-12 05:37 UTC, yuaanlin commented on pages/docs/basic-features/data-fetching/get-server-side-props.mdx
> +# getServerSideProps（服務器端渲染）
```suggestion
# getServerSideProps
```

getServerSideProps 這個 API 的中文意思並不是 Server Side Rendering

2022-09-12 05:37 UTC, yuaanlin commented on pages/docs/basic-features/data-fetching/get-server-side-props.mdx
> +如果您從頁面導出名為 getServerSideProps（服務器端渲染）的函數，Next.js 將使用 getServerSideProps 返回的數據在每個請求上預渲染此頁面。
```suggestion
如果您從頁面匯出名為 getServerSideProps 的函數，Next.js 將使用 getServerSideProps 回傳的資料在每個請求上提前渲染此頁面。
```

可能要幫忙注意一下簡繁詞彙的使用

2022-09-12 05:37 UTC, yuaanlin commented on pages/docs/basic-features/data-fetching/get-server-side-props.mdx
> +>請注意，無論呈現類型如何，任何`props`都將傳遞給頁面組件，並且可以在初始 HTML 中在客戶端查看。這是為了讓頁面正確[hydrated](https://reactjs.org/docs/react-dom.html#hydrate)。確保您沒有在 `props` 中傳遞任何不應在客戶端上可用的敏感信息
```suggestion
>請注意，無論呈現類型如何，任何`props`都將傳遞給頁面元件，並且可以在初始 HTML 中在客戶端查看。這是為了讓頁面正確[hydrated](https://reactjs.org/docs/react-dom.html#hydrate)。確保您沒有在 `props` 中傳遞任何不應在客戶端上可用的敏感資料。
```

2022-09-12 05:37 UTC, yuaanlin commented on pages/docs/basic-features/data-fetching/get-server-side-props.mdx
> +當你直接請求這個頁面時，`getServerSideProps` 在請求的時候運行，這個頁面會和返回的 props 一起預渲染
```suggestion
當你直接請求這個頁面時，`getServerSideProps` 在請求的時候運行，這個頁面會和返回的 props 一起提前渲染。
```

2022-09-12 05:37 UTC, yuaanlin commented on pages/docs/basic-features/data-fetching/get-server-side-props.mdx
> +請注意，您必須將 `getServerSideProps` 作為獨立函數導出 - 如果將 `getServerSideProps` 添加為頁面組件的props，它將**不起作用**。
```suggestion
請注意，您必須將 `getServerSideProps` 作為獨立函數匯出 - 如果將 `getServerSideProps` 添加為頁面元件的 props ，它將**不起作用**。
```

2022-09-14 03:18 UTC, yuaanlin requested changes

2022-09-14 03:18 UTC, yuaanlin commented on pages/docs/basic-features/data-fetching/overview.mdx
> +    <b>SSR: 伺服器選染</b>
```suggestion
    <b>SSR: 伺服器渲染</b>
```

2022-09-14 03:18 UTC, yuaanlin commented on pages/docs/basic-features/data-fetching/get-server-side-props.mdx
> +當您想從服務器獲取數據時，可能很容易使用 [API 路由](/docs/api-routes/introduction)，然後從 `getServerSideProps` 調用該 API 路由。 這是一種不必要且低效的方法，因為它會由於服務器上運行的 `getServerSideProps` 和 API Routes 而導致發出額外的請求。
```suggestion
當您想從伺服器取得資料時，可能很容易使用 [API 路由](/docs/api-routes/introduction)，然後從 `getServerSideProps` 調用該 API 路由。 這是一種不必要且低效的方法，因為它會由於伺服器上運行的 `getServerSideProps` 和 API Routes 而導致發出額外的請求。
```

2022-09-14 03:18 UTC, yuaanlin commented on pages/docs/basic-features/data-fetching/get-server-side-props.mdx
> +以下範例顯示如何在請求時獲取數據並預渲染結果。
```suggestion
以下範例顯示如何在請求時取得資料並提前渲染結果。
```

2022-09-14 03:18 UTC, yuaanlin commented on pages/docs/basic-features/data-fetching/get-server-side-props.mdx
> +如果在執行`getServerSideProps`發生錯誤，他將會顯示`pages/500.js`頁面。 查看此文件[500 page](/docs/advanced-features/custom-error-page#500-page) 了解有關如何創建它的更多信息.在開發過程中，不會使用此文件
```suggestion
如果在執行 `getServerSideProps` 發生錯誤，他將會顯示 `pages/500.js` 頁面。 查看此文件 [500 page](/docs/advanced-features/custom-error-page#500-page) 了解有關如何創建它的更多資訊。需要注意的是，在開發過程中不會使用此檔案，而是直接顯示錯誤訊息。
```

2022-09-14 03:18 UTC, yuaanlin commented on pages/docs/basic-features/data-fetching/overview.mdx
> +    <small>在你的頁面中添加TypeScript</small>
```suggestion
    <small>在你的頁面中添加 TypeScript</small>
```

2022-09-14 03:18 UTC, yuaanlin commented on pages/docs/basic-features/data-fetching/overview.mdx
> +  <a href="/docs/basic-features/typescript.pages">
```suggestion
  <a href="/docs/basic-features/typescript">
```

2022-09-14 03:18 UTC, yuaanlin commented on pages/docs/basic-features/data-fetching/overview.mdx
> +    <small>了解有關 Next.js 中路由的更多信息</small>
```suggestion
    <small>了解有關 Next.js 中路由的更多資訊</small>
```

2022-09-14 03:18 UTC, yuaanlin commented on pages/docs/basic-features/data-fetching/get-server-side-props.mdx
> +`getServerSideProps` 會回傳JSON資料讓請求頁面去渲染. 所有的執行緒全部都由 Next.js自動化掌握, 所以只要你定義了`getServerSideProps`，你就不需要做任何額外的事情。
```suggestion
`getServerSideProps` 會回傳 JSON 資料讓請求頁面去渲染。 所有的執行緒全部都由 Next.js 自動化處理，所以只要你定義了 `getServerSideProps`，你就不需要做任何額外的事情。
```

2022-09-14 03:18 UTC, yuaanlin commented on pages/docs/basic-features/data-fetching/get-server-side-props.mdx
> +- 當你在客戶端發送請求是透過 [`next/link`](/docs/api-reference/next/link.md)切換或是 [`next/router`](/docs/api-reference/next/router.md), Next.js 就會發送API請求到伺服器並運行`getServerSideProps`
```suggestion
- 當你在客戶端發送請求是透過 [`next/link`](/docs/api-reference/next/link.md)切換或是 [`next/router`](/docs/api-reference/next/router.md), Next.js 就會發送 API 請求到伺服器並運行`getServerSideProps`。
```

2022-09-14 03:18 UTC, yuaanlin commented on pages/docs/basic-features/data-fetching/get-server-side-props.mdx
> +>請注意，無論呈現類型如何，任何`props`都將傳遞給頁面組件，並且可以在初始 HTML 中在客戶端查看。這是為了讓頁面正確[hydrated](https://reactjs.org/docs/react-dom.html#hydrate)。確保您沒有在 `props` 中傳遞任何不應在客戶端上可用的敏感信息
```suggestion
>請注意，無論呈現類型如何，任何`props`都將傳遞給頁面組件，並且可以在初始 HTML 中在客戶端查看。這是為了讓頁面正確[hydrated](https://reactjs.org/docs/react-dom.html#hydrate)。確保您沒有在 `props` 中傳遞任何不應在客戶端上可用的敏感資訊。
```

2022-09-16 17:46 UTC, t7yang requested changes

2022-09-16 17:46 UTC, t7yang commented on pages/docs/basic-features/data-fetching/get-server-side-props.mdx
> +`getServerSideProps` 只會在伺服器端運行並不會在瀏覽器執行. 如果這個頁面使用`getServerSideProps`, 這時:
```suggestion
`getServerSideProps` 只會在伺服器端運行並不會在瀏覽器執行。如果這個頁面使用 `getServerSideProps` ，這時：
```

2022-09-16 17:46 UTC, t7yang commented on pages/docs/basic-features/data-fetching/get-server-side-props.mdx
> +當你直接請求這個頁面時，`getServerSideProps` 在請求的時候運行，這個頁面會和返回的 props 一起提前渲染。
```suggestion
當你直接請求這個頁面時， `getServerSideProps` 在請求的時候運行，這個頁面會和回傳的 props 一起提前渲染。
```

2022-09-16 17:46 UTC, t7yang commented on pages/docs/basic-features/data-fetching/get-server-side-props.mdx
> +`getServerSideProps` 只能在**page**資料夾中匯出. 你不能在不是page的資料夾匯出這將會報錯.
```suggestion
`getServerSideProps` 只能在 **page** 資料夾中匯出。你不能在不是 page 的資料夾匯出這將會報錯。
```

有太多標點符號錯誤，請重新檢視全文。

2022-09-16 17:46 UTC, t7yang commented on pages/docs/basic-features/data-fetching/get-server-side-props.mdx
> +[`getServerSideProps` API 文件](/docs/api-reference/data-fetching/get-server-side-props) 涵蓋所有可以使用的參數和props。
```suggestion
[`getServerSideProps` API 文件](/docs/api-reference/data-fetching/get-server-side-props) 涵蓋所有可以使用的參數和 props。
```

kerning 記得全文檢查過。

2022-09-16 17:46 UTC, t7yang commented on pages/docs/basic-features/data-fetching/get-server-side-props.mdx
> +當你的頁面資料必須在請求時間時拿到你應該使用`getServerSideProps`。這可能是由於請求的數據或屬性的性質 (例如 `authorization` headers 或是 geo location). 當頁面使用 `getServerSideProps`將會在請求時伺服器提前渲染，並且僅在以下情況下被緩存 [cache-control headers 已配置](/docs/going
```suggestion
若基於資料的特性使然（如 `authorization` 標頭或地理位置等資訊），使得渲染頁面的資料必須在請求時先取得，則必須使用 `getServerSideProps` 函數。當頁面使用 `getServerSideProps` 時，將會在收到請求時由伺服器端提前渲染，並且只在 [cache-control 標頭已組態](/docs/going-to-production#caching)的情況下被快取。
```

2022-09-16 17:46 UTC, t7yang commented on pages/docs/basic-features/data-fetching/get-server-side-props.mdx
> +當你的頁面資料必須在請求時間時拿到你應該使用`getServerSideProps`。這可能是由於請求的數據或屬性的性質 (例如 `authorization` headers 或是 geo location). 當頁面使用 `getServerSideProps`將會在請求時伺服器提前渲染，並且僅在以下情況下被緩存 [cache-control headers 已配置](/docs/going
狐狸說：剩下的部分請自行潤飾及完善

2022-09-18 15:13 UTC, yuaanlin approved these changes

2022-09-18 15:13 UTC, merged