Translate /learn/foundations/how-nextjs-works/index
yuaanlin/nextjs.tw pull request #47
Opened 2022-09-11 13:52 UTC by lucy70381

Translate /learn/foundations/how-nextjs-works/index

2022-09-12 05:20 UTC, yuaanlin requested changes
Thanks for the contribution! There is one sentence can be translated more natively. Please help us to improve it!

謝謝你的貢獻！有一句話可以翻譯的更佳流暢，請幫助我們優化它！

2022-09-12 05:20 UTC, yuaanlin commented on pages/learn/foundations/how-nextjs-works/index.mdx
> +在本課程的開始，我們討論了對於您如何建置和構建您的應用程式 React 是如何相對地自由 - 有多種方式可使用 React 來建置應用程式。Next.js 提供了一個框架來構建您的應用，可有助於加速開發過程和最終應用程式的優化。
這句話翻譯的不太通順，建議可以先理解原文的意思以後用自己的話重新說一遍，不需要讓每個字和順序都和原文一模一樣沒關係！

2022-09-13 16:40 UTC, lucy70381 commented on pages/learn/foundations/how-nextjs-works/index.mdx
> +在本課程的開始，我們討論了對於您如何建置和構建您的應用程式 React 是如何相對地自由 - 有多種方式可使用 React 來建置應用程式。Next.js 提供了一個框架來構建您的應用，可有助於加速開發過程和最終應用程式的優化。
The code has been updated, please check.

2022-09-14 01:01 UTC, yuaanlin approved these changes
Nice work! Thanks for the contribution.

2022-09-14 01:01 UTC, merged

2022-09-14 03:55 UTC, yuaanlin commented
https://nextjs.tw/learn/foundations/how-nextjs-works