feat: bundling頁面翻譯。問答區塊
yuaanlin/nextjs.tw pull request #62
Opened 2022-09-22 01:17 UTC by YONG-LIN-LIANG

Features include translation in bundling page and Quiz area.

2022-09-25 06:37 UTC, yuaanlin requested changes

2022-09-25 06:37 UTC, yuaanlin commented on pages/learn/foundations/how-nextjs-works/bundling.mdx
> +開發者利用將他們的應用程式拆分成多個模組、組件及函式，來建立更大規模的應用程式。
```suggestion
## 什麼是模組打包？

開發者利用將他們的應用程式拆分成多個模組、組件及函式，來建立更大規模的應用程式。
```

兩個不同的 Markdown 元素之間需要加入空行。

2022-09-25 06:37 UTC, yuaanlin commented on pages/learn/foundations/how-nextjs-works/bundling.mdx
> +導出或導入這些內部模組及第三方包來建立一個複雜度高的檔案相依的網站。
```suggestion
導出或導入這些內部模組及第三方套件來建立一個複雜度高的檔案相依的網站。
```

2022-09-25 06:37 UTC, yuaanlin commented on pages/learn/foundations/how-nextjs-works/bundling.mdx
> +模組打包意旨用來解析有多個依賴的網站及合併（或打包）檔案（模組），成為對瀏覽器來說優化過後的包的一個完整過程，且能在使用者訪問網頁時，以最低限度的請求來索取網頁資源。
```suggestion
模組打包意旨用來解析有多個依賴的網站及合併（或打包）檔案（模組），成為瀏覽器優化產物的一個完整過程，且能在使用者訪問網頁時，以最低限度的請求來索取網頁資源。
```

2022-09-25 06:37 UTC, yuaanlin commented on pages/learn/foundations/how-nextjs-works/bundling.mdx
> +
記得在最後面加入 TranslatedBy 元件

2022-09-26 01:21 UTC, YONG-LIN-LIANG commented on pages/learn/foundations/how-nextjs-works/bundling.mdx
> +
Problem solved, please check it out！

2022-09-28 07:14 UTC, yuaanlin approved these changes

2022-09-28 07:14 UTC, merged