2022/10/3 index.mdx 完成
yuaanlin/nextjs.tw pull request #78
Opened 2022-10-03 11:35 UTC by yenbigbear

2022-10-04 02:19 UTC, yuaanlin requested changes

2022-10-04 02:19 UTC, yuaanlin commented on pages/learn/basics/create-nextjs-app/setup.mdx
> +運行開發服務器
```suggestion
運行開發伺服器
```

2022-10-04 02:19 UTC, yuaanlin commented on pages/learn/basics/create-nextjs-app/setup.mdx
> +要創建 Next.js 應用程式，請打開終端，`cd`進入要在其中創建應用式的目錄，然後執行以下指令：
```suggestion
要創建 Next.js 應用程式，請打開終端機，輸入 `cd` 指令來進入要在其中創建應用式的目錄，然後執行以下指令：
```

2022-10-04 02:19 UTC, yuaanlin commented on pages/learn/basics/create-nextjs-app/setup.mdx
> +在後台，它使用[`create-next-app`][4]工具，引導您創建 Next.js 應用程式。它通過`--example`參數使用[這個模板][5]。
```suggestion
在這個指令的背後，它使用 [`create-next-app`][4] 工具，引導您創建 Next.js 應用程式。它通過`--example` 參數使用[這個模板][5]。
```

2022-10-04 02:19 UTC, yuaanlin commented on pages/learn/basics/create-nextjs-app/setup.mdx
> +您現在有一個名為nextjs-blog. 讓我們cd進入它：
```suggestion
您現在有一個名為 `nextjs-blog` 的資料夾，讓我們使用 `cd` 指令來進入它：
```

2022-10-04 02:19 UTC, yuaanlin commented on pages/learn/basics/create-nextjs-app/setup.mdx
> +這會在端口3000上啟動 Next.js 應用程序的“開發服務器”（稍後會詳細介紹） 。
```suggestion
這會在 3000 端口上啟動 Next.js 應用程式的「開發伺服器」（稍後會詳細介紹） 。
```

2022-10-04 02:19 UTC, yuaanlin commented on pages/learn/basics/create-nextjs-app/setup.mdx
> +然後，運行以下命令：
```suggestion
然後，執行以下指令：
```

2022-10-04 02:19 UTC, yuaanlin commented on pages/learn/basics/create-nextjs-app/setup.mdx
> +讓我們檢查一下它是否有效。從瀏覽器打開http://localhost:3000 。
```suggestion
讓我們檢查一下它是否有效。 從瀏覽器打開 `http://localhost:3000` 。
```

2022-10-04 02:19 UTC, yuaanlin commented on pages/learn/basics/create-nextjs-app/setup.mdx
> +[1]: https://nodejs.org/en/ "Node.js安裝"
```suggestion
[1]: https://nodejs.org/en/ "Node.js 安裝"
```

2022-10-04 02:19 UTC, yuaanlin commented on pages/learn/basics/create-nextjs-app/setup.mdx
> +[2]: https://gitforwindows.org/ "Git for Windows下載"
```suggestion
[2]: https://gitforwindows.org/ "Git for Windows 下載"
```

2022-10-04 02:19 UTC, yuaanlin commented on pages/learn/basics/create-nextjs-app/setup.mdx
> +#### 創建 Next.js 應用
```suggestion
#### 創建 Next.js 應用程式
```

2022-10-04 02:19 UTC, yuaanlin commented on pages/learn/basics/create-nextjs-app/setup.mdx
> +如果您作業系統使用的是 Windows，我們建議您[下載 Git for Windows][2]並使用它附帶的 Git Bash，它支援本教學中特定於 UNIX 的命令。[適用於 Linux 的 Windows 子系統 (WSL)][3]是另一種選擇。
```suggestion
如果您作業系統使用的是 Windows，我們建議您[下載 Git for Windows][2]並使用它附帶的 Git Bash，它支援本教學中特定於 UNIX 的指令。[適用於 Linux 的 Windows 子系統 (WSL)][3]是另一種選擇。
```

2022-10-08 02:47 UTC, yenbigbear commented
2022/10/8 create-nextjs-app/setup.mdx OK

2022-10-09 04:15 UTC, yuaanlin approved these changes
Nice work!

2022-10-09 04:15 UTC, merged