10/5 navigat-pages
yuaanlin/nextjs.tw pull request #85
Opened 2022-10-05 10:03 UTC by iga00257

/learn/basics/navigate-between-pages translate 
1.setup
2.pages-in-nextjs
3.link-component
4. client-side

2022-10-10 07:26 UTC, yuaanlin requested changes
謝謝你的翻譯！這邊有一些問題需要你幫我們進行調整：

1. 盡可能使用繁體中文的用詞，而不是簡體中文的用詞。例如：

`代碼` -> `程式碼`
`用戶` -> `使用者`
`應用程序` -> `應用程式`
`用戶端` -> `客戶端`
`文件` -> `檔案`

2. 請不要提交 `package-lock.json` 檔案。你會產生這個檔案是因為你是用了 `npm install` 來安裝套件，但我們的專案是使用 `pnpm` 來進行套件管理，所以不會有 `package-lock.json` 檔案。

3. 使用中文的全形標點符號： `，` 而不是 `,`， `。` 而不是 `.`。

4. 注意 Kerning —— 也就是在英文詞和中文字之間記得空格，例如：

```
在同一個Next.js應用程式
```

是錯誤的用法。

```
在同一個 Next.js 應用程式
```

是正確的用法。

2022-10-10 07:26 UTC, yuaanlin commented on pages/learn/basics/navigate-between-pages/client-side.mdx
> +### 代碼拆分和預先取回連結
```suggestion
### 程式碼拆分和提前載入連結
```

2022-10-10 07:26 UTC, yuaanlin commented on pages/learn/basics/navigate-between-pages/client-side.mdx
> +如果您使用了 `<a href="...">` 而不是 `<Link href="...">`，則在點擊鏈接時背景顏色將被清除，因為瀏覽器會進行完全刷新
```suggestion
如果您使用了 `<a href="...">` 而不是 `<Link href="...">`，則在點擊連結時背景顏色將被清除，因為瀏覽器會進行完全重新整理。
```

2022-10-10 07:26 UTC, yuaanlin commented on pages/learn/basics/navigate-between-pages/client-side.mdx
> +這表明瀏覽器沒有加載整個頁面並且用戶端跳轉正常運作
```suggestion
這表明瀏覽器沒有載入整個頁面並且用戶端跳轉正常運作。
```

2022-10-10 07:26 UTC, yuaanlin commented on pages/learn/basics/navigate-between-pages/client-side.mdx
> +- 打開瀏覽器的開發者工具並把`<html>`中`background`的 CSS屬性改成`yellow`.
```suggestion
- 打開瀏覽器的開發者工具並把 `<html>` 中 `background` 的 CSS 屬性改成 `yellow`。
```

2022-10-10 07:26 UTC, yuaanlin commented on components/LearnRoutes.json
> +            "title": "Link 組件",
```suggestion
            "title": "Link 元件",
```

2022-10-10 07:26 UTC, yuaanlin commented on components/LearnRoutes.json
> +            "title": "用戶端的跳轉",
```suggestion
            "title": "客戶端的跳轉",
```

2022-10-10 07:26 UTC, yuaanlin commented on pages/learn/basics/navigate-between-pages/client-side.mdx
> +`Link` 組件可以允許在同一個Next.js應用程式中的兩個頁面之間進行**用戶端的頁面跳轉**
```suggestion
`Link` 元件可以允許在同一個 Next.js 應用程式中的兩個頁面之間進行**客戶端的頁面跳轉**。
```

2022-10-10 07:26 UTC, yuaanlin commented on pages/learn/basics/navigate-between-pages/client-side.mdx
> +Next.js 會自動進行代碼拆分, 所以每個頁面只加載該頁面所需的內容。 這意味著在渲染主頁時，初始化的過程不會載入其他頁面的代碼。
```suggestion
Next.js 會自動進行程式碼拆分，所以每個頁面只載入該頁面所需的內容。 這意味著在渲染首頁時，初始化的過程不會載入其他頁面的程式碼。
```

2022-10-10 07:26 UTC, yuaanlin commented on pages/learn/basics/navigate-between-pages/client-side.mdx
> +即使您有數百個頁面，這也可以確保主頁快速加載。
```suggestion
即使您有數百個頁面，這也可以確保首頁快速加載。
```

2022-10-10 07:26 UTC, yuaanlin commented on pages/learn/basics/navigate-between-pages/client-side.mdx
> +僅載入您請求的頁面也意味著頁面是獨立的代碼。 如果某個頁面拋出錯誤，應用程式的其餘部分仍然可以正常運作
```suggestion
僅載入您請求的頁面也意味著頁面是獨立的程式碼。 如果某個頁面拋出錯誤，應用程式的其餘部分仍然可以正常運作
```

2022-10-10 07:26 UTC, yuaanlin commented on pages/learn/basics/navigate-between-pages/client-side.mdx
> +此外，在 Next.js 的生產版本中，每當`Link`組件出現在瀏覽器的顯示裝置中時，Next.js 都會在後台自動**預先加載**鏈接頁面的代碼。當您單擊鏈接時，目標頁面的代碼已經在背景執行加載，頁面轉換幾乎是即時的！
```suggestion
此外，在 Next.js 的生產版本中，每當 `Link` 組件出現在瀏覽器的顯示裝置中時，Next.js 都會在後台自動**提前載入**連結頁面的程式碼。當您單擊連結時，目標頁面的代碼已經在背景執行加載，所以頁面轉換幾乎是即時的！
```

2022-10-10 07:26 UTC, yuaanlin commented on pages/learn/basics/navigate-between-pages/client-side.mdx
> +Next.js會 通過代碼拆分,用戶端頁面跳轉,和預先加載的機制來自動優化您的應用程序以取得最佳效能.
```suggestion
Next.js 會通過程式碼拆分、客戶端頁面跳轉和提前載入的機制來自動優化您的應用程式以取得最佳效能。
```

2022-10-10 07:26 UTC, yuaanlin commented on pages/learn/basics/navigate-between-pages/client-side.mdx
> +您可以在 `pages` 下將路由創建為文件，並使用內置的 `Link` 組件, 這個模式是不需要路由相關函式庫的.
```suggestion
您可以在 `pages` 下將路由創建為檔案，並使用內建的 `Link` 組件，這個模式是不需要路由相關函式庫的。
```

2022-10-10 07:26 UTC, yuaanlin commented on pages/learn/basics/navigate-between-pages/client-side.mdx
> +如果有個用戶打開他的瀏覽器並跳轉到`your-blog.com/posts/first-post`頁面. JavaScript在初始化時會載入什麼進這個頁面?
```suggestion
如果有個使用者打開他的瀏覽器並跳轉到 `your-blog.com/posts/first-post` 頁面，JavaScript 在初始化時會載入什麼進這個頁面？
```

2022-10-10 07:26 UTC, yuaanlin commented on pages/learn/basics/navigate-between-pages/client-side.mdx
> +        <QuizOption text="加載整個應用程序的 JavaScript"/>
```suggestion
        <QuizOption text="加載整個應用程式的 JavaScript"/>
```

2022-10-13 01:27 UTC, iga00257 commented
Hi, 我是Discord裡面的橘貓 跟您學習React Basic的那位同學 也是這part翻譯的撰寫者
感謝你的建議, 我預計這個週末會做修改 感謝！

Yuanlin Lin ***@***.***> 於 2022年10月10日 週一 下午3:26寫道：

> ***@***.**** requested changes on this pull request.
>
> 謝謝你的翻譯！這邊有一些問題需要你幫我們進行調整：
>
>    1. 盡可能使用繁體中文的用詞，而不是簡體中文的用詞。例如：
>
> 代碼 -> 程式碼
> 用戶 -> 使用者
> 應用程序 -> 應用程式
> 用戶端 -> 客戶端
> 文件 -> 檔案
>
>    1.
>
>    請不要提交 package-lock.json 檔案。你會產生這個檔案是因為你是用了 npm install 來安裝套件，但我們的專案是使用
>    pnpm 來進行套件管理，所以不會有 package-lock.json 檔案。
>    2.
>
>    使用中文的全形標點符號： ， 而不是 ,， 。 而不是 .。
>    3.
>
>    注意 Kerning —— 也就是在英文詞和中文字之間記得空格，例如：
>
> 在同一個Next.js應用程式
>
> 是錯誤的用法。
>
> 在同一個 Next.js 應用程式
>
> 是正確的用法。
> ------------------------------
>
> In pages/learn/basics/navigate-between-pages/client-side.mdx
> <https://github.com/yuaanlin/nextjs.tw/pull/85#discussion_r990969713>:
>
> > +客戶端導航意味著頁面轉換時使用 _JavaScript_，這比瀏覽器內建的預設跳轉方法更快。
> +
> +
> +這裡有一個簡單的方法可以驗證它：
> +- 打開瀏覽器的開發者工具並把`<html>`中`background`的 CSS屬性改成`yellow`.
> +- 點擊連結以在兩個頁面中來回切換
> +- 您會看到黃色背景在頁面轉換之間持續存在
> +
> +這表明瀏覽器沒有加載整個頁面並且用戶端跳轉正常運作
> +This shows that the browser does _not_ load the full page and client-side navigation is working.
> +
> +![](https://nextjs.org/static/images/learn/navigate-between-pages/client-side.gif)
> +
> +如果您使用了 `<a href="...">` 而不是 `<Link href="...">`，則在點擊鏈接時背景顏色將被清除，因為瀏覽器會進行完全刷新
> +
> +### 代碼拆分和預先取回連結
>
> ⬇️ Suggested change
>
> -### 代碼拆分和預先取回連結
> +### 程式碼拆分和提前載入連結
>
> ------------------------------
>
> In pages/learn/basics/navigate-between-pages/client-side.mdx
> <https://github.com/yuaanlin/nextjs.tw/pull/85#discussion_r990969894>:
>
> > +## 用戶端的頁面跳轉
> +`Link` 組件可以允許在同一個Next.js應用程式中的兩個頁面之間進行**用戶端的頁面跳轉**
> +客戶端導航意味著頁面轉換時使用 _JavaScript_，這比瀏覽器內建的預設跳轉方法更快。
> +
> +
> +這裡有一個簡單的方法可以驗證它：
> +- 打開瀏覽器的開發者工具並把`<html>`中`background`的 CSS屬性改成`yellow`.
> +- 點擊連結以在兩個頁面中來回切換
> +- 您會看到黃色背景在頁面轉換之間持續存在
> +
> +這表明瀏覽器沒有加載整個頁面並且用戶端跳轉正常運作
> +This shows that the browser does _not_ load the full page and client-side navigation is working.
> +
> +![](https://nextjs.org/static/images/learn/navigate-between-pages/client-side.gif)
> +
> +如果您使用了 `<a href="...">` 而不是 `<Link href="...">`，則在點擊鏈接時背景顏色將被清除，因為瀏覽器會進行完全刷新
>
> ⬇️ Suggested change
>
> -如果您使用了 `<a href="...">` 而不是 `<Link href="...">`，則在點擊鏈接時背景顏色將被清除，因為瀏覽器會進行完全刷新
> +如果您使用了 `<a href="...">` 而不是 `<Link href="...">`，則在點擊連結時背景顏色將被清除，因為瀏覽器會進行完全重新整理。
>
> ------------------------------
>
> In pages/learn/basics/navigate-between-pages/client-side.mdx
> <https://github.com/yuaanlin/nextjs.tw/pull/85#discussion_r990970023>:
>
> > \ No newline at end of file
> +## 用戶端的頁面跳轉
> +`Link` 組件可以允許在同一個Next.js應用程式中的兩個頁面之間進行**用戶端的頁面跳轉**
> +客戶端導航意味著頁面轉換時使用 _JavaScript_，這比瀏覽器內建的預設跳轉方法更快。
> +
> +
> +這裡有一個簡單的方法可以驗證它：
> +- 打開瀏覽器的開發者工具並把`<html>`中`background`的 CSS屬性改成`yellow`.
> +- 點擊連結以在兩個頁面中來回切換
> +- 您會看到黃色背景在頁面轉換之間持續存在
> +
> +這表明瀏覽器沒有加載整個頁面並且用戶端跳轉正常運作
>
> ⬇️ Suggested change
>
> -這表明瀏覽器沒有加載整個頁面並且用戶端跳轉正常運作
> +這表明瀏覽器沒有載入整個頁面並且用戶端跳轉正常運作。
>
> ------------------------------
>
> In pages/learn/basics/navigate-between-pages/client-side.mdx
> <https://github.com/yuaanlin/nextjs.tw/pull/85#discussion_r990970261>:
>
> > \ No newline at end of file
> +## 用戶端的頁面跳轉
> +`Link` 組件可以允許在同一個Next.js應用程式中的兩個頁面之間進行**用戶端的頁面跳轉**
> +客戶端導航意味著頁面轉換時使用 _JavaScript_，這比瀏覽器內建的預設跳轉方法更快。
> +
> +
> +這裡有一個簡單的方法可以驗證它：
> +- 打開瀏覽器的開發者工具並把`<html>`中`background`的 CSS屬性改成`yellow`.
>
> ⬇️ Suggested change
>
> -- 打開瀏覽器的開發者工具並把`<html>`中`background`的 CSS屬性改成`yellow`.
> +- 打開瀏覽器的開發者工具並把 `<html>` 中 `background` 的 CSS 屬性改成 `yellow`。
>
> ------------------------------
>
> In components/LearnRoutes.json
> <https://github.com/yuaanlin/nextjs.tw/pull/85#discussion_r990970482>:
>
> >              "path": "/learn/basics/navigate-between-pages/pages-in-nextjs"
>            },
>            {
> -            "title": "Link Component",
> +            "title": "Link 組件",
>
> ⬇️ Suggested change
>
> -            "title": "Link 組件",
> +            "title": "Link 元件",
>
> ------------------------------
>
> In components/LearnRoutes.json
> <https://github.com/yuaanlin/nextjs.tw/pull/85#discussion_r990970622>:
>
> >              "path": "/learn/basics/navigate-between-pages/link-component"
>            },
>            {
> -            "title": "Client-Side Navigation",
> +            "title": "用戶端的跳轉",
>
> ⬇️ Suggested change
>
> -            "title": "用戶端的跳轉",
> +            "title": "客戶端的跳轉",
>
> ------------------------------
>
> In pages/learn/basics/navigate-between-pages/client-side.mdx
> <https://github.com/yuaanlin/nextjs.tw/pull/85#discussion_r990970963>:
>
> > \ No newline at end of file
> +## 用戶端的頁面跳轉
> +`Link` 組件可以允許在同一個Next.js應用程式中的兩個頁面之間進行**用戶端的頁面跳轉**
>
> ⬇️ Suggested change
>
> -`Link` 組件可以允許在同一個Next.js應用程式中的兩個頁面之間進行**用戶端的頁面跳轉**
> +`Link` 元件可以允許在同一個 Next.js 應用程式中的兩個頁面之間進行**客戶端的頁面跳轉**。
>
> ------------------------------
>
> In pages/learn/basics/navigate-between-pages/client-side.mdx
> <https://github.com/yuaanlin/nextjs.tw/pull/85#discussion_r990971512>:
>
> > +
> +這裡有一個簡單的方法可以驗證它：
> +- 打開瀏覽器的開發者工具並把`<html>`中`background`的 CSS屬性改成`yellow`.
> +- 點擊連結以在兩個頁面中來回切換
> +- 您會看到黃色背景在頁面轉換之間持續存在
> +
> +這表明瀏覽器沒有加載整個頁面並且用戶端跳轉正常運作
> +This shows that the browser does _not_ load the full page and client-side navigation is working.
> +
> +![](https://nextjs.org/static/images/learn/navigate-between-pages/client-side.gif)
> +
> +如果您使用了 `<a href="...">` 而不是 `<Link href="...">`，則在點擊鏈接時背景顏色將被清除，因為瀏覽器會進行完全刷新
> +
> +### 代碼拆分和預先取回連結
> +
> +Next.js 會自動進行代碼拆分, 所以每個頁面只加載該頁面所需的內容。 這意味著在渲染主頁時，初始化的過程不會載入其他頁面的代碼。
>
> ⬇️ Suggested change
>
> -Next.js 會自動進行代碼拆分, 所以每個頁面只加載該頁面所需的內容。 這意味著在渲染主頁時，初始化的過程不會載入其他頁面的代碼。
> +Next.js 會自動進行程式碼拆分，所以每個頁面只載入該頁面所需的內容。 這意味著在渲染首頁時，初始化的過程不會載入其他頁面的程式碼。
>
> ------------------------------
>
> In pages/learn/basics/navigate-between-pages/client-side.mdx
> <https://github.com/yuaanlin/nextjs.tw/pull/85#discussion_r990971610>:
>
> > +- 打開瀏覽器的開發者工具並把`<html>`中`background`的 CSS屬性改成`yellow`.
> +- 點擊連結以在兩個頁面中來回切換
> +- 您會看到黃色背景在頁面轉換之間持續存在
> +
> +這表明瀏覽器沒有加載整個頁面並且用戶端跳轉正常運作
> +This shows that the browser does _not_ load the full page and client-side navigation is working.
> +
> +![](https://nextjs.org/static/images/learn/navigate-between-pages/client-side.gif)
> +
> +如果您使用了 `<a href="...">` 而不是 `<Link href="...">`，則在點擊鏈接時背景顏色將被清除，因為瀏覽器會進行完全刷新
> +
> +### 代碼拆分和預先取回連結
> +
> +Next.js 會自動進行代碼拆分, 所以每個頁面只加載該頁面所需的內容。 這意味著在渲染主頁時，初始化的過程不會載入其他頁面的代碼。
> +
> +即使您有數百個頁面，這也可以確保主頁快速加載。
>
> ⬇️ Suggested change
>
> -即使您有數百個頁面，這也可以確保主頁快速加載。
> +即使您有數百個頁面，這也可以確保首頁快速加載。
>
> ------------------------------
>
> In pages/learn/basics/navigate-between-pages/client-side.mdx
> <https://github.com/yuaanlin/nextjs.tw/pull/85#discussion_r990971750>:
>
> > +- 您會看到黃色背景在頁面轉換之間持續存在
> +
> +這表明瀏覽器沒有加載整個頁面並且用戶端跳轉正常運作
> +This shows that the browser does _not_ load the full page and client-side navigation is working.
> +
> +![](https://nextjs.org/static/images/learn/navigate-between-pages/client-side.gif)
> +
> +如果您使用了 `<a href="...">` 而不是 `<Link href="...">`，則在點擊鏈接時背景顏色將被清除，因為瀏覽器會進行完全刷新
> +
> +### 代碼拆分和預先取回連結
> +
> +Next.js 會自動進行代碼拆分, 所以每個頁面只加載該頁面所需的內容。 這意味著在渲染主頁時，初始化的過程不會載入其他頁面的代碼。
> +
> +即使您有數百個頁面，這也可以確保主頁快速加載。
> +
> +僅載入您請求的頁面也意味著頁面是獨立的代碼。 如果某個頁面拋出錯誤，應用程式的其餘部分仍然可以正常運作
>
> ⬇️ Suggested change
>
> -僅載入您請求的頁面也意味著頁面是獨立的代碼。 如果某個頁面拋出錯誤，應用程式的其餘部分仍然可以正常運作
> +僅載入您請求的頁面也意味著頁面是獨立的程式碼。 如果某個頁面拋出錯誤，應用程式的其餘部分仍然可以正常運作
>
> ------------------------------
>
> In pages/learn/basics/navigate-between-pages/client-side.mdx
> <https://github.com/yuaanlin/nextjs.tw/pull/85#discussion_r990972086>:
>
> > +
> +這表明瀏覽器沒有加載整個頁面並且用戶端跳轉正常運作
> +This shows that the browser does _not_ load the full page and client-side navigation is working.
> +
> +![](https://nextjs.org/static/images/learn/navigate-between-pages/client-side.gif)
> +
> +如果您使用了 `<a href="...">` 而不是 `<Link href="...">`，則在點擊鏈接時背景顏色將被清除，因為瀏覽器會進行完全刷新
> +
> +### 代碼拆分和預先取回連結
> +
> +Next.js 會自動進行代碼拆分, 所以每個頁面只加載該頁面所需的內容。 這意味著在渲染主頁時，初始化的過程不會載入其他頁面的代碼。
> +
> +即使您有數百個頁面，這也可以確保主頁快速加載。
> +
> +僅載入您請求的頁面也意味著頁面是獨立的代碼。 如果某個頁面拋出錯誤，應用程式的其餘部分仍然可以正常運作
> +此外，在 Next.js 的生產版本中，每當`Link`組件出現在瀏覽器的顯示裝置中時，Next.js 都會在後台自動**預先加載**鏈接頁面的代碼。當您單擊鏈接時，目標頁面的代碼已經在背景執行加載，頁面轉換幾乎是即時的！ [...]

2022-10-15 03:21 UTC, merged